name: admin_panel
description: admin_panel
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  async: ^2.8.1
  auto_route: ^7.7.1
  bloc: ^8.1.2
  built_collection: ^5.1.1
  built_value: ^8.6.1
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.6
  freezed: ^2.3.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  # http_mock_adapter: ^0.4.2
  inspector: ^2.0.1
  intl: ^0.18.0
  # j_linter: ^0.0.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  jwt_decoder: ^2.0.1
  logger: ^2.0.1
  mobx: ^2.2.0
  pluto_grid: ^7.0.2
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.0.5
  ui_kit:
    path: packages/ui_kit
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.5
  built_value_generator: ^8.6.1
  dart_code_metrics: ^5.7.5
  # dart_style: ^2.2.4
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  icon_font_generator:
    git:
      url: https://github.com/Gaurav192/icon_font_generator.git
      ref: file_path_fix
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/assets/
  # line_length: 120

  # Optional
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true # Disable when push
  # main_locale: ru
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: AppLocalizationsIntl
