name: ui_kit
description: admin_panel_ui
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.3
  # http_mock_adapter: ^0.4.2
  inspector: ^2.0.1
  intl: ^0.18.0
  pluto_grid: ^7.0.2
  # j_linter: ^0.0.6
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  build_runner: ^2.4.5
  built_value_generator: ^8.6.1
  dart_code_metrics: ^5.7.5
  # dart_style: ^2.2.4
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  icon_font_generator:
    git:
      url: https://github.com/Gaurav192/icon_font_generator.git
      ref: file_path_fix

flutter:
  uses-material-design: true
  assets:
    - assets/icons/section_icons/
    - assets/icons/system_icons/
    - assets/fonts/
  fonts:
    - family: SystemIcons
      fonts:
        - asset: assets/fonts/system_icons.ttf

flutter_gen:
  output: lib/assets/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: UiKitAssets
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true # Disable when push
  # main_locale: ru
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: AppLocalizationsIntl
